name: cleanup
channels:
  - anaconda
  - conda-forge
  - defaults
  - plotly
  - pytorch
  - nvidia

dependencies:
  - python
  - datasets
  - einops
  - ipykernel
  - ipywidgets
  - jaxtyping
  - jupyter
  - lmfit
  - nbformat>=4.2.0  # for plotly
  - numpy
  - pandas
  - plotly>=5.15
  - pytorch
  - seaborn>=0.12.2
  - tqdm
  - pip
  - pip:
    - transformer-lens
    - git+https://github.com/callummcdougall/CircuitsVis.git#subdirectory=python
