python fig1_resid_onto_H0_2_lineplot.py
python fig2_H0_2_cleanup_barplot.py
python fig3_patch_v_input_cleaners.py
python fig4_H2_X_lineplots.py
python fig5_attn_pattern_H0_2.py
python fig6_OVs_of_H0_X.py
# python fig7_resample_ablation.py
python fig8_bos_nonbos_proj_ratios.py
python fig9_DLA_barplots.py
# python fig10_DLA_resid_onto_H0_2.py
